language: java
script:
  - mvn javadoc:aggregate
  - mvn verify
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: ioio-bundle/target/ioio-bundle-*-bundle.zip
    skip_cleanup: true
    keep_history: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: ioio-bundle/target/ioio-bundle-*-bundle.zip
    skip_cleanup: true
    keep_history: true
    draft: true
    on:
      branch: master