language: java
deploy:
  - provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  - provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ioio-bundle/target/ioio-bundle-*-bundle.zip
  skip_cleanup: true
  keep_history: true
  on:
    branch: master