management:
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true

logging.level:
  root: INFO
  com.ioio.jsontools: DEBUG

server:
  port: 9090
  servlet:
    context-path: /core
